config/routes.rb
Projet::Application.routes.draw do
  get "panier/ajouter/:objet_id" => 'panier#ajouter', as: :ajouter_objet_au_panier

  resources :objets
  resources :categories

  root 'objets#index'

end

app/models/objet.rb
class Objet < ActiveRecord::Base
  belongs_to :categorie
  validates_presence_of :categorie, :on => :create, :message => "doit être renseignée"
end

app/controllers/objets_controller.rb
class ObjetsController < ApplicationController
  before_action :set_objet, only: [:show, :edit, :update, :destroy]

  # GET /objets
  # GET /objets.json
  def index
    @objets = Objet.all
  end

  # GET /objets/1
  # GET /objets/1.json
  def show
    session[:heure] = Time.now
  end

  # GET /objets/new
  def new
    @objet = Objet.new
  end

  # GET /objets/1/edit
  def edit
  end

  # POST /objets
  # POST /objets.json
  def create
    @objet = Objet.new(objet_params)

    respond_to do |format|
      if @objet.save
        format.html { redirect_to @objet, notice: 'Objet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @objet }
      else
        format.html { render action: 'new' }
        format.json { render json: @objet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objets/1
  # PATCH/PUT /objets/1.json
  def update
    respond_to do |format|
      if @objet.update(objet_params)
        format.html { redirect_to @objet, notice: 'Objet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @objet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objets/1
  # DELETE /objets/1.json
  def destroy
    @objet.destroy
    respond_to do |format|
      format.html { redirect_to objets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objet
      @objet = Objet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objet_params
      params.require(:objet).permit(:libelle, :valeur, :categorie_id)
    end
end

app/helpers/objets_helper.rb
module ObjetsHelper
end

app/views/objets/_form.html.erb
<%= form_for(@objet) do |f| %>
  <% if @objet.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><%= pluralize(@objet.errors.count, "error") %> prohibited this objet from being saved:</strong>

      <ul>
      <% @objet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :libelle %><br>
    <%= f.text_field :libelle %>
  </div>
  <div class="field">
    <%= f.label :valeur %><br>
    <%= f.text_field :valeur %>
  </div>

  <!-- Ajout d'un champ pour choisir la catégorie -->
  <div class="field">
    <%= f.label :categorie_id %><br>
    <%= f.collection_select :categorie_id, 
              Categorie.all, :id, :libelle, {prompt: "Choisissez une catégorie"} %>
  </div>

  <!-- Envoi d'un fichier de photo -->
  <div class="field">
    <%= f.label :fichier_image %>    
    <%= f.file_field :fichier_image %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objets/edit.html.erb
<h1>Modification d'un objet</h1>

<%= render 'form' %>


<pre>
  Ici, on affiche l'heure qu'il était quand on a fait le show
  <%= session[:heure] %>
</pre>

<%= link_to 'Show', @objet %> |
<%= link_to 'Back', objets_path %>

app/views/objets/index.html.erb
<h1>Listing objets</h1>

<table>
  <thead>
    <tr>
      <th>Libelle</th>
      <th>Valeur</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @objets.each do |objet| %>
      <tr>
        <td><%= objet.libelle %></td>
        <td><%= objet.valeur %></td>
        <td><%= link_to 'Show', objet %></td>
        <td><%= link_to 'Edit', edit_objet_path(objet) %></td>
        <td><%= link_to 'Destroy', objet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
             <!-- UJS : Unobstrusive JavaScript -->
             <button class="btn btn-success ajouter_au_panier"                     
                       id="<%= objet.id %>">
               Ajouter au panier
             </button>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>Contenu du panier</h3>
<div id="contenu_du_panier">Ici, on affichera le retour ajax</div>

<%= link_to 'New Objet', new_objet_path, class:"btn btn-success" %>

app/views/objets/new.html.erb
<h1>New objet</h1>

<%= render 'form' %>

<%= link_to 'Back', objets_path %>

app/views/objets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Libelle:</strong>
  <%= @objet.libelle %>
</p>

<p>
  <strong>Valeur:</strong>
  <%= @objet.valeur %>
</p>

<p>
  <strong>Catégorie:</strong>
  <% if @objet.categorie %>
    <%= link_to @objet.categorie.libelle, @objet.categorie %>
  <% end %>
</p>

<%= link_to 'Edit', edit_objet_path(@objet) %> |
<%= link_to 'Back', objets_path %>


<pre>
<%= request.original_fullpath %>
</pre>