config/routes.rb
Projet::Application.routes.draw do
  get "panier/ajouter/:objet_id" => 'panier#ajouter', as: :ajouter_objet_au_panier

  resources :objets
  resources :categories

  root 'objets#index'

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_categorie, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Categorie.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @categorie = Categorie.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @categorie = Categorie.new(categorie_params)

    respond_to do |format|
      if @categorie.save
        sauve_fichier_pour @categorie
        format.html { redirect_to @categorie, notice: 'Categorie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @categorie }
      else
        format.html { render action: 'new' }
        format.json { render json: @categorie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @categorie.update(categorie_params)
        sauve_fichier_pour @categorie
        format.html { redirect_to @categorie, notice: 'Categorie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @categorie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @categorie.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  def sauve_fichier_pour(o)
    return unless @uploaded_io
    # Création d'un répertoire pour stocker l'image
    chemin_stockage_fichiers = Rails.root.join('public', 'uploads', o.class.table_name).to_s
    FileUtils.mkdir_p chemin_stockage_fichiers

    # Stockage
    FileUtils.mv @uploaded_io.tempfile, chemin_stockage_fichiers+"/#{o.id}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorie
      @categorie = Categorie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorie_params
      @uploaded_io = params[:categorie].delete(:fichier_image)
      params.require(:categorie).permit(:libelle, :fichier_image, objets_attributes:[:id, :libelle, :valeur, :_destroy])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= nested_form_for @categorie, html:{class:"-dropzone"} do |f| %>
  <% if @categorie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorie.errors.count, "error") %> prohibited this categorie from being saved:</h2>

      <ul>
      <% @categorie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :libelle %><br>
    <%= f.text_field :libelle %>
  </div>

  <div class="field">
    <%= f.label :fichier_image %><br>
    <%= f.file_field :fichier_image %>
  </div>

  <div class="field well">
    <%= f.fields_for :objets %>
    <%= f.link_to_add "Ajouter un objet", :objets %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_objet_fields.html.erb
<div class="well">

  <div class="field">
    <%= f.label :libelle %><br>
    <%= f.text_field :libelle %>
  </div>
  <div class="field">
    <%= f.label :valeur %><br>
    <%= f.text_field :valeur %>
  </div>

  <%= f.link_to_remove "Supprimer cet objet" %>
</div>

app/views/categories/edit.html.erb
<h1>Editing categorie</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorie %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Libelle</th>
      <th>Fichier image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |categorie| %>
      <tr>
        <td><%= categorie.libelle %></td>
        <td><%= categorie.fichier_image %></td>
        <td><%= link_to 'Show', categorie %></td>
        <td><%= link_to 'Edit', edit_categorie_path(categorie) %></td>
        <td><%= link_to 'Destroy', categorie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categorie', new_categorie_path %>

app/views/categories/new.html.erb
<h1>New categorie</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Libelle:</strong>
  <%= @categorie.libelle %>
</p>

<p>
  <strong>Fichier image:</strong>
  <%= @categorie.fichier_image %>
</p>

<p>
  <strong>Liste des objets</strong>
  <ul>    
    <% @categorie.objets.each do |objet| %>
      <li><%= link_to objet.libelle, objet %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Image</strong>
  <%= image_tag "../uploads/categories/#{@categorie.id}" %>
</p>

<%= link_to 'Edit', edit_categorie_path(@categorie) %> |
<%= link_to 'Back', categories_path %>